version: '2'
services:
  cordula:
    image: msprunck/cordula:latest
    build:
      context: ../
      dockerfile: docker/cordula/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_URI: "mongodb://admin:crdl@mongodb:27017/cordula"
      SERVER_PORT: 3000
      CLIENT_ID: 0ZE6WlsV37O07xHsBD6dUikKBtw4wvVB
      CLIENT_SECRET: ${CLIENT_SECRET}
      AUTHORIZATION_URL: https://cordula.auth0.com/authorize
      SCOPE: openid
      TOKEN_NAME: id_token
    depends_on:
      - mongodb
  mongodb:
    image: tutum/mongodb:3.2
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data
    environment:
      MONGODB_PASS: "crdl"
      MONGODB_DATABASE: "cordula"
volumes:
  mongodb-data:
    external: false
