version: '2'
services:
  cordula:
    image: msprunck/cordula:latest
    build:
      context: ../
      dockerfile: docker/cordula/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_URI: "mongodb://admin:crdl@mongodb:27017/cordula"
      SERVER_PORT: 3000
    depends_on:
      - mongodb
  mongodb:
    image: tutum/mongodb:3.2
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data
    environment:
      MONGODB_PASS: "crdl"
      MONGODB_DATABASE: "cordula"
volumes:
  mongodb-data:
    external: false
